### PR TITLE
add a png icon

### PR DESCRIPTION
**Pull request by flynnduism**
Uses the porter hat for a small, transparent and scalable activity bar icon 

Signed-off-by: flynnduism <flynnduism@gmail.com>

### CODE REVIEW

**Comment by flynnduism** [comment]
Changed this because I had foolishly designed a VS Code activity bar icon, rather than a marketplace one. 

This is now a full color icon:

porter

**Comment by carolynvs** [comment]
So this is what shows up at the top left on a marketplace webpage? The blue line at the bottom I assume is because our marketplace header is set to that color?

**Comment by flynnduism** [comment]
> I'm wondering how it would look inside VS Code?

Not sure where this would appear _inside_ the editor, Ivan just asked for a Marketplace avatar style image. 

If there is an in-app Porter image I will make a different icon separate to this, because this is too detailed to work as an icon. For something of that size I think a standalone hat, a 'P' or an outline of the Portermoji character might work.

icon

**Comment by carolynvs** [comment]
When browsing extensions to install or those you have already installed, I see a logo.

Screen Shot 2020-02-05 at 10 15 05 AM

**Comment by flynnduism** [comment]
> When browsing extensions to install or those you have already installed, I see a logo.
> 
> Screen Shot 2020-02-05 at 10 15 05 AM

The main logo of the Porter character should work just fine in that setting in-app. Large enough space for the marketplace image above. @carolynvs shall I keep or remove that purple stripe at the bottom? I'm happy either way.

**Comment by carolynvs** [comment]
I think the stripe at the bottom would be hard to see on the black background. So my vote would be for without it.

**Comment by flynnduism** [comment]
porter

Border line removed!

**Pull request merged**
